[package]
name = "wikipedia"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bzip2 = "0.4.4"
html-escape = "0.2.13"
indicatif = "0.17.8"
threadpool = "1.8.1"
xml-rs = "0.8.20"
